
services:
  comfyui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: comfyui_container
    ports:
      - "8188:8188"
    restart: unless-stopped
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - /home/ptech/comfyui/models:/app/models
      - /home/ptech/comfyui/output:/app/output
      - /home/ptech/comfyui/input:/app/input
      - /home/ptech/comfyui/custom_nodes:/app/custom_nodes
    stdin_open: true
    tty: true